package con.com.soaint.sgd
 
import co.com.soaint.sgd.model.MedioRecepcion


rule "Oficio"
no-loop true
when
medioRecepcion : MedioRecepcion($codMedio : codMedioRecepcion == "TL-DOCOF" )

then
     medioRecepcion.setCodUnidaTiempo("UNID-TID");
	 medioRecepcion.setTiempoRespuesta("10");  
	 medioRecepcion.setInicioConteo("DSH");
 update( medioRecepcion );
end

rule "Tutela"
no-loop true
when
medioRecepcion : MedioRecepcion($codMedio : codMedioRecepcion == "TL-DOCT" )

then
     medioRecepcion.setCodUnidaTiempo("UNID-TID");
	 medioRecepcion.setTiempoRespuesta("10"); 
	 medioRecepcion.setInicioConteo("DSH");  
 update( medioRecepcion );
end

rule "Derecho de Petición"
no-loop true
when
medioRecepcion : MedioRecepcion($codMedio : codMedioRecepcion == "TL-DOCDP" )

then
     medioRecepcion.setCodUnidaTiempo("UNID-TID");
	 medioRecepcion.setTiempoRespuesta("10");   
	 medioRecepcion.setInicioConteo("DSH");
 update( medioRecepcion );
end

rule "Invitación"
no-loop true
when
medioRecepcion : MedioRecepcion($codMedio : codMedioRecepcion == "TL-DOCII" )

then
     medioRecepcion.setCodUnidaTiempo("UNID-TID");
	 medioRecepcion.setTiempoRespuesta("10");   
	 medioRecepcion.setInicioConteo("DSH");
 update( medioRecepcion );
end

rule "Demanda"
no-loop true
when
medioRecepcion : MedioRecepcion($codMedio : codMedioRecepcion == "TL-DOCDM" )

then
     medioRecepcion.setCodUnidaTiempo("UNID-TID");
	 medioRecepcion.setTiempoRespuesta("10");   
	 medioRecepcion.setInicioConteo("DSH");
 update( medioRecepcion );
end

rule "Factura"
no-loop true
when
medioRecepcion : MedioRecepcion($codMedio : codMedioRecepcion == "TL-DOCF" )

then
     medioRecepcion.setCodUnidaTiempo("UNID-TID");
	 medioRecepcion.setTiempoRespuesta("10");
	 medioRecepcion.setInicioConteo("DSH");   
 update( medioRecepcion );
end
rule "Investigación"
no-loop true
when
medioRecepcion : MedioRecepcion($codMedio : codMedioRecepcion == "TL-DOCIE" )

then
     medioRecepcion.setCodUnidaTiempo("UNID-TID");
	 medioRecepcion.setTiempoRespuesta("10"); 
	 medioRecepcion.setInicioConteo("DSH");  
 update( medioRecepcion );
end
rule "Denuncia"
no-loop true
when
medioRecepcion : MedioRecepcion($codMedio : codMedioRecepcion == "TL-DOCDN" )

then
     medioRecepcion.setCodUnidaTiempo("UNID-TID");
	 medioRecepcion.setTiempoRespuesta("10"); 
	 medioRecepcion.setInicioConteo("DSH");  
 update( medioRecepcion );
end
rule "Recurso"
no-loop true
when
medioRecepcion : MedioRecepcion($codMedio : codMedioRecepcion == "TL-DOCR" )

then
     medioRecepcion.setCodUnidaTiempo("UNID-TID");
	 medioRecepcion.setTiempoRespuesta("10");  
	 medioRecepcion.setInicioConteo("DSH"); 
 update( medioRecepcion );
end
rule "PQRSD"
no-loop true
when
medioRecepcion : MedioRecepcion($codMedio : codMedioRecepcion == "TL-DOCP" )

then
     medioRecepcion.setCodUnidaTiempo("UNID-TID");
	 medioRecepcion.setTiempoRespuesta("10"); 
	 medioRecepcion.setInicioConteo("DSH");  
 update( medioRecepcion );
end
rule "Acta"
no-loop true
when
medioRecepcion : MedioRecepcion($codMedio : codMedioRecepcion == "TL-DOCA" )

then
     medioRecepcion.setCodUnidaTiempo("UNID-TID");
	 medioRecepcion.setTiempoRespuesta("10");
	 medioRecepcion.setInicioConteo("DSH");   
 update( medioRecepcion );
end
rule "Circular"
no-loop true
when
medioRecepcion : MedioRecepcion($codMedio : codMedioRecepcion == "TL-DOCC" )

then
     medioRecepcion.setCodUnidaTiempo("UNID-TID");
	 medioRecepcion.setTiempoRespuesta("10"); 
	 medioRecepcion.setInicioConteo("DSH");  
 update( medioRecepcion );
end
rule "Memorando"
no-loop true
when
medioRecepcion : MedioRecepcion($codMedio : codMedioRecepcion == "TL-DOCM" )

then
     medioRecepcion.setCodUnidaTiempo("UNID-TID");
	 medioRecepcion.setTiempoRespuesta("10");
	 medioRecepcion.setInicioConteo("DSH");   
 update( medioRecepcion );
end
