//created on: Aug 22, 2017
package rules

import co.com.soaint.sgd.model.Redireccion


rule "Redireccionar"
no-loop true
    when 
    redireccionar : Redireccion(numRedirecciones <= 3 )    //conditions
    then
     redireccionar.setRespuestaRedireccion(true);
     update( redireccionar );    //actions

end

rule "No redireccionar"
no-loop true
    when
    redireccionar : Redireccion(numRedirecciones > 3 )     //conditions
    then
     redireccionar.setRespuestaRedireccion(false);
     update( redireccionar );    //actions    //actions

end
