package co.com.soaint.jbpm.domains;

/**
 * This class was automatically generated by the data modeler tool.
 */

import java.io.Serializable;

public class Redireccion implements Serializable {
	
	static final long serialVersionUID = 1L;
	int numRedirecciones;
	boolean respuestaRedireccion;
	
	public Redireccion() {
		super();
		this.numRedirecciones = numRedirecciones;		
	}
	public int getNumRedirecciones() {
		return numRedirecciones;
	}
	public void setNumRedirecciones(int numRedirecciones) {
		this.numRedirecciones = numRedirecciones;
	}
	public boolean isRespuestaRedireccion() {
		return respuestaRedireccion;
	}
	public void setRespuestaRedireccion(boolean respuestaRedireccion) {
		this.respuestaRedireccion = respuestaRedireccion;
	}
	
	

}
